version: 2
updates:
  # Client dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    assignees:
      - "Mateeb-Haider"
    labels:
      - "dependencies"
      - "client"

  # Server dependencies
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    assignees:
      - "Mateeb-Haider"
    labels:
      - "dependencies"
      - "server"